title = 'CAMBioMed'
baseURL = 'https://cambiomed-biodiversa.com/'
languageCode = 'en-us'
disableKinds = ['taxonomy', 'term']

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'