## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------
title = 'CAMBioMed'
baseURL = 'https://cambiomed-biodiversa.com/'
languageCode = 'en-us'
theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = true
#canonifyURLs = "true"

# Local
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = [ "taxonomy", "section" ]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]