title = 'CAMBioMed'
baseURL = 'https://cambiomed-biodiversa.com/'
languageCode = 'en-us'
disableKinds = ['taxonomy', 'term']

defaultContentLanguage = "en"
sectionPagesMenu = "main"
#paginate.paperSize = 10


# [menu]
# [[menu.nav]]
# identifier = "home"
# name = "Home"
# url = "/"
# weight = 1

# [[menu.nav]]
# identifier = "about"
# name = "About"
# url = "/about/"
# weight = 2

# [[menu.nav]]
# identifier = "connect"
# name = "Connect"
# url = "/connect/"
# weight = 

[params]
site_logo = "images/cambiomed-logo.png"
date_format = ":date_full"


###########
# Sitemap #
###########
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"


################
# Social Media #
################
[params.ananke.social.follow]
networks = [
  "bluesky",
  "instagram",
]

[params.ananke.social.bluesky]
username = "cambiomed-biodiversa.com"

[params.ananke.social.instagram]
username = "cambiomed_biodiversa"


###########
# Modules #
###########
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
